### ISSUE TITLE
[Backend] Configurar Cadastro de Usuários

### ISSUE THREAD

**Issue by GabrielPen1do** [ICEI-PUC-Minas-PMV-ADS/psg-ads-n-tiam-2024-2-gerenciador-escolar#10]
**Configurar cadastro de usuários:** 

- Implementar a lógica para registrar novos usuários no Firebase.
- Cada tipo de usuário (aluno, professor, diretora) deve ser identificado durante o registro e armazenado no banco de dados.
- Implementar permissões específicas para cada tipo de usuário no banco de dados.

**Critério de Aceitação:**

- [x] Usuários conseguem se cadastrar com sucesso e são diferenciados por tipo (aluno, professor, diretora).

Essa issue faz parte da epic #8 .

**Comment by Davidsb04** [comment]
Foram implementadas todas as funcionalidades, incluindo o tipo de usuário, conforme o exemplo:

1 - Secretary;
2-  Teacher;
3 - Student/Parents.
