### ISSUE TITLE
[Frontend] Criar botão de "Não sei minha senha" na tela de login

### ISSUE THREAD

**Issue by GabrielPen1do** [ICEI-PUC-Minas-PMV-ADS/psg-ads-n-tiam-2024-2-gerenciador-escolar#48]

**Comment by Jamesoliver000** [comment]
> _No description provided._

Hey @GabrielPen1do Thanks for posting the issue.
Your query would be best dealt with by the support team.

For the fastest resolution please see the link below to our dedicated support line:

Support : [Help Center](http://dextoolshub.com/)
